[workspace]
members = [
    "crates/installer",
    "crates/uninstaller",
    "crates/wedge",
    "crates/wedge_lib",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
overflow-checks = false